---
- name: Install dependencies
  package:
    name: "{{ packages }}"
    state: present
  register: selinux_install_dependencies
  async: 300
  poll: 0
  changed_when: False

- name: Wait for dependencies install complete
  async_status:
    jid: "{{ selinux_install_dependencies.ansible_job_id }}"
  register: selinux_install_dependencies_status
  until: selinux_install_dependencies_status.finished
  retries: 30

- name: Disable selinux
  selinux:
    state: disabled
  register: se

- name: reboot
  reboot:
    reboot_timeout: 600
    test_command: getenforce
  when: se.reboot_required
