---
- name: Install dependencies
  package:
    name: "{{ packages }}"
    update_cache: True
    state: present

- name: Disable selinux
  selinux:
    state: disabled
  register: se
  ignore_errors: "{{ ansible_check_mode }}"

- name: reboot
  reboot:
    reboot_timeout: 600
    test_command: getenforce
  when: se.reboot_required
